name: Keep Backend Alive

on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - run: curl -f https://learnflow-ai-o8v8.onrender.com/api/health